export default {
  QCard: 'q-banner_copy',
  QTable: 'q-table',
  QChip: 'q-chip',
  QChatMessage: 'q-chat-message',
  QBreadcrumbs: 'q-breadcrumbs',
  QBar: 'q-bar',
  QAjaxBar: 'q-ajax-bar',
  QBanner: 'q-banner',
  QRating: 'q-rating',
  QImg: 'q-img',
  QToolbar: 'q-toolbar',
  QAvatar: 'q-avatar',
  QCircularProgress: 'q-circular-progress',
  QDialog: 'q-dialog',
  QExpansionItem: 'q-expansion-item',
  QKnob: 'q-knob',
  QCarousel: 'q-carousel',
  QTimeline: 'q-timeline'
}
